version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run tests
          command: yarn test

      - persist_to_workspace:
          root: ./
          paths:
            - ./build

  deploy:
    machine:
        enabled: true

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ./

      - run:
          name: Deploy
          command: script/server

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
